### ISSUE TITLE
Add support for records

### ISSUE THREAD

**Issue by pigulla** [HurricaneJames/react-immutable-proptypes#12]
It'd be nice if your library supported them.

 E.g., like so:

```js
import React from 'react';
import ImmutablePropTypes from 'react-immutable-proptypes';

class FooComponent extends React.Component {
    static propTypes = {
        blogPost: ImmutablePropTypes.record.isRequired
    };

    // ...
}
```

**Comment by Lexicality** [comment]
:+1:, even better if I could specify the record itself.
eg
```javascript
import React from 'react';
import ImmutablePropTypes from 'react-immutable-proptypes';

import { BlogPost } from './store'

class FooComponent extends React.Component {
    static propTypes = {
        blogPost: ImmutablePropTypes.record(BlogPost).isRequired
    };

    // ...
}
```

**Comment by HurricaneJames** [comment]
@Lexicality I added initial support for this in v1.3.0. There is now a `record` prop type checker that checks to see if the prop is record. There is also a `recordOf` checker that validates specific keys. Please take a look and let me know if it fits your needs.

**Comment by zerkms** [comment]
@HurricaneJames I can confirm both `record` and `recordOf` work for me, thanks!

**Comment by HurricaneJames** [comment]
Awesome
