### ISSUE TITLE
What about useing es2015 and only defining it in development evirnoment 

### ISSUE THREAD

**Issue by dexbol** [HurricaneJames/react-immutable-proptypes#14]
Hi, @HurricaneJames 

React only validate protoType in development environment . So could you define the functions in the condition (process.env.NODE_ENV == 'production')?

And React encourages using babel, so could you use es2015 .

If you agree me , I will pull a request ASAP.

**Comment by HurricaneJames** [comment]
I do not understand what you are getting at. If you have a pull request I would be glad to review it.
