### ISSUE TITLE
validate shape of Map

### ISSUE THREAD

**Issue by indeyets** [HurricaneJames/react-immutable-proptypes#15]
Currently, I can either validate that something is a `Map` or that something `contains` specific keys/values. 

Can I do both at the same time?
I want to validate that something is an immutable Map with specific keys, which have values of specific types.

At first, I had an idea that `mapOf` would do the thing, but it validates each of map's values against pattern.

**Comment by sentience** [comment]
I have this question too.

**Comment by HurricaneJames** [comment]
If it contains specific keys/values, then isn't it a Map or a Map descendant by default? What would be the scenario where you want to verify specific key/values and specifically care about the implementing class?

And sorry for the delay. I recently changed jobs and moved from the east coast to the west... ie. I have been a bad project maintainer.

**Comment by MatthewHerbst** [comment]
You can apply the same logic as used in React PropTypes. Look at [this SO question](http://stackoverflow.com/questions/34362898/proptypes-check-of-object-with-dynamic-keys) for the how, and refer to #17 for making sure you realize you will get a normal JS type.

**Comment by HurricaneJames** [comment]
I think the SO question actually references a slightly different problem, ie verifying that something is a `Map<string, Object>` (map from string to Object). That is an interesting problem, and not one that is handled by this library currently. I would be more than happy to accept a PR for such a feature though.

**Comment by MatthewHerbst** [comment]
@HurricaneJames to generalize a little more, the SO questions asks about how you can verify type and/or format of the keys of a map, not just the values of those keys.

**Comment by hartzis** [comment]
please check out PR #24 to see if it fits the requested functionality

**Comment by HurricaneJames** [comment]
This should be addressed by #24, which has been merged/published as v1.7.0.
