### ISSUE TITLE
Using specific Record type as PropType

### ISSUE THREAD

**Issue by delenius** [HurricaneJames/react-immutable-proptypes#19]
Suppose I am using Immutable.Record to define my own types, say

```javascript
var Person = Immutable.Record({age: null, name: null})
```

is it possible to specify that a prop has to be an instance of my Person type, rather than just "Immutable.PropTypes.record"? This would be a big win for type-checking and documentation.

**Comment by zerkms** [comment]
I initially expected that `ImmutablePropTypes.recordOf(Person)` would do the job, but apparently it does not.

So I'm doubling having it.

**Comment by HurricaneJames** [comment]
Sorry for taking so long to look at this. I recently moved to California to start a new job and have been caught up in all the stuff that goes with moving and changing jobs. I will look at this over the weekend.

**Comment by HurricaneJames** [comment]
I think you can just use the default `React.PropTypes.instanceOf(Person)`, right?

**Comment by delenius** [comment]
@HurricaneJames yeah you're right :+1: 
Feel free to close this.
