### ISSUE TITLE
Verifying a map and its contents.

### ISSUE THREAD

**Issue by AlexTes** [HurricaneJames/react-immutable-proptypes#22]
I wrote the following PropType. As I understand it, ImmutablePropTypes.map let's me verify it's a map and `user: ImmutablePropTypes.map` works fine. As does the below with the `ImmutablePropTypes.mapOf()` part removed. However because I'd like to verify user is an immutable map, judging by your listOf example this would be the way to do that. Unfortunately the following fails:
```javascript
static propTypes = {
	user: ImmutablePropTypes.mapOf(
		ImmutablePropTypes.contains({
			name: PropTypes.string.isRequired,
			nickname: PropTypes.string.isRequired,
			picture: PropTypes.string.isRequired
		})
	)
};
```
with 
```
Warning: Failed propType: Invalid prop '0' of type 'number' supplied to 'InformationSummary', expected an Immutable.js Iterable. Check the render method of 'Personal'.
```

Could you clarify what I'm doing wrong here?

**Comment by hartzis** [comment]
Same issue as #15?

**Comment by AlexTes** [comment]
Yes, duplicate. Closing.

**Comment by HurricaneJames** [comment]
Thank you for closing this. Yes, it is basically the same question. I still do not quite understand why you would need to check both that it is, specifically an Immutable.Map and that it has specific values types for specific key types. At that point it basically is a Map. About the only case I can think of where it might conflict would be where you have an Immutable.Map with numeric keys which might get confused with a List. At that point, it might be time to look into something like Flow.

**Comment by hartzis** [comment]
@AlexTes does PR #24 solve your use case?

**Comment by AlexTes** [comment]
Yes @hartzis. If I read your code correctly PR #24 verifies the prop is an Immutable.Map and recursively verifies that whatever keys you wish to be checked also are what you expect them to be.

@HurricaneJames I got confused because of two (possibly bad) assumptions. One: other immutable datatypes might also have key/value pairs therefor one cannot assume something with a shape is a map. For example `Immutable.Set<NumOrString, String>`, which you might want to confirm is a Set with a certain shape, not a Map with a shape and vice versa.

Two: I had no idea of how `React.PropTypes.arrayOf` works. Seeing your example using ListOf instead of List I assumed the 'Of' part in 'ListOf' meant it should always be used in conjunction with a shape / contains. Helped by there being nothing to hint at the `React.PropTypes.arrayOf(React.PropTypes.number)` way of verifying PropTypes.

In addition it would be a small nicety to have a possible failing check explain the prop is not in fact a map, instead of saying `Warning: Failed propType: Invalid prop '0' of type 'string' supplied to 'InformationSummary', expected an Immutable.js Iterable.`

**Comment by hartzis** [comment]
@AlexTes #24 adds `immutableClassName` to the error now. Specifically for `mapContains` it will say `Map` now.

> `supplied to \`${componentName}\`, expected an Immutable.js ${immutableClassName}.`
