### ISSUE TITLE
IPT equivalent to `oneOf`

### ISSUE THREAD

**Issue by djskinner** [HurricaneJames/react-immutable-proptypes#25]
Is there currently a way to verify that an Immutable list contains specific elements?

This would be roughly equivalent to `React.PropTypes.oneOf(['CLOSED', 'OPEN'])`

**Comment by HurricaneJames** [comment]
I'm not sure I understand the question. `PropTypes.oneOf` checks a single prop against an enumeration of options.

To test that a list contains a specific set of elements you can use `ImmutablePropTypes.listOf` to verify that every element of the list is of the specified type.

It is possible to test that specific elements are specific values via `ImmutablePropTypes.contains`. I do not recommend doing it, but you can say:

```
ImmutablePropTypes.contains({
0: PropTypes.string,
1: PropTypes.number,
2: PropTypes.oneOf(['OPEN', 'CLOSED']),
// ... etc ...
};
```

**Comment by djskinner** [comment]
Let's say I have a list of 'valid' colors:

`let validColors = ['GREEN', 'RED', 'BLUE', 'YELLOW']`

Then I have a component that takes a list of 'selected' colors as a prop, for example:

`let myProp = ['GREEN', 'RED']`

I could verify that the prop was a list of strings with `ImmutablePropTypes.listOf(PropTypes.string)`

However, what I'd really like to do is verify that all of the values in the list were one of the 'valid' colors, such that `['GREEN', 'RED']` would be valid but `['GREEN', 'BLACK']` would not.

Looking back at the documentation, I imagine I'd have tried something like this but presumably it didn't work:

```
    propTypes: {
        myRequiredImmutableList: ImmutablePropTypes.listOf(
            ImmutablePropTypes.oneOf(['GREEN', 'RED', 'BLUE', 'YELLOW']`})
        ).isRequired
    }
```

Using the second example you gave, it might be achieved like this:

```
ImmutablePropTypes.contains({
0: PropTypes.oneOf(['OPEN', 'CLOSED']),
1: PropTypes.oneOf(['OPEN', 'CLOSED']),
2: PropTypes.oneOf(['OPEN', 'CLOSED']),
// ... etc ...
};
```

But of course that isn't desirable.

**Comment by HurricaneJames** [comment]
I think it would work if you did:

```javascript
propTypes: {
  myRequiredImmutableList: ImmutablePropTypes.listOf(
    // note React.Proptypes, not ImmutablePropTypes
    React.PropTypes.oneOf(['GREEN', 'RED', 'BLUE', 'YELLOW']).isRequired // require no nulls
  ).isRequired // require the list
}
```

**Comment by djskinner** [comment]
Yes, of course. Thanks.
