### ISSUE TITLE
.oneOfType()?

### ISSUE THREAD

**Issue by busticated** [HurricaneJames/react-immutable-proptypes#26]
hey there - thanks for a super-helpful lib! :clap:

wondering if there's already a way to express this:

    /*
        assuming immutable data like:
            [
                { one: true },
                { one: true },
                { two: true },
                { one: true },
                { two: true }
            ]
    */
    ImmutablePropTypes.listOf(
        PropTypes.oneOfType([ // <-- i think this gums things up but not sure how yet
            ImmutablePropTypes.mapContains(shapes.one),
            ImmutablePropTypes.mapContains(shapes.two)
        ])
    )

and if not, if you would be open to a PR for it?

**Comment by HurricaneJames** [comment]
As long a `shapes` is defined somewhere, I think this should work. Also, you might want to use `ImmutablePropTypes.contains`, unless you want to also verify that `{ one: true }` and `{ two: true }` are also `Immutable.Map`.

How is your shapes object defined?

```
const shapes = {
  one: { one: PropTypes.bool },
  two: { two: PropTypes.bool },
};
```

**Comment by busticated** [comment]
whoops - sorry for the delayed response here. you are correct: that works just fine. i have no idea what i bungled on my first pass but coming back to it today i was able to just uncomment what i had and it ran as expected. sorry for the false-alarm and thanks for taking a look!
