### ISSUE TITLE
Is .shape() deprecated?

### ISSUE THREAD

**Issue by contra** [HurricaneJames/react-immutable-proptypes#29]
The documentation says shape was changed to contains, but it still exists in the code and the exposed API. Are you planning on removing shape any time soon?

Trying to do

```js
PropTypes = {
  ...React.PropTypes,
  ...ImmutablePropTypes
}
```

**Comment by HurricaneJames** [comment]
It is deprecated, and I did forget to remove it in the 1.2.x branch. I will probably remove it whenever 2.0.x lands, if it ever lands. In general, it is better to use `contains` because `shape` conflicts with popular linters like es-lint.
