### ISSUE TITLE
isRequired on single types

### ISSUE THREAD

**Issue by Aesthetickz** [HurricaneJames/react-immutable-proptypes#3]
Why can't we use ImmutablePropTypes.List.isRequired?
Do I have to use listOf?

Kind regards,

Niels

**Comment by HurricaneJames** [comment]
I suppose I could add class matchers. However, you can already accomplish this with `React.PropTypes.instanceOf(Immutable.List).isRequired`.

**Comment by HurricaneJames** [comment]
Do you still want this matcher or was the proposed solution good enough? If not, I'm going to close out this ticket.

**Comment by Aesthetickz** [comment]
It would be nice but you can close this issue ;)

**Comment by cesarandreu** [comment]
@HurricaneJames if you're open to it, I'd like `ImmutablePropTypes.List.isRequired`. Every immutable.js class would be awesome. 

If you're using `ImmutablePropTypes` already and you're not creating any Immutable classes inside of your component, you'll end up having to require immutable.js if you wanna specify a property is an Immutable instance without specifying the structure.

Although I'd understand why you might not want to include em. It just seems a bit more convenient, but it's definitely not the strongest argument.

**Comment by HurricaneJames** [comment]
Implemented and merged. Just published on npmjs as version 0.1.7.

I implemented it as `ImmutablePropTypes.list` (lowercase) because that keeps the syntax more in line with `React.PropTypes`. I also created primitives for all the other types that have a checker in Immutable.js.

**Comment by cesarandreu** [comment]
Thanks!

**Comment by HurricaneJames** [comment]
No Problem. I think you all are right, it is just a convenience, but a very nice one.
