### ISSUE TITLE
Confused as to when to use ImmutablePropTypes.contains

### ISSUE THREAD

**Issue by ericlau-solid** [HurricaneJames/react-immutable-proptypes#31]
I am somewhat confused as to proper use here. In this code snippet:

```
'productItems': ImmutablePropTypes.mapOf({
        'upc': PropTypes.string,
        'erpItemNumber': PropTypes.string,
        'onHandQuantity': PropTypes.number,
        'vendorQuantity': PropTypes.number,
        'disabled': PropTypes.bool,
        'hideOnSite': PropTypes.bool,
        'size': PropTypes.string,
        'sizeOrder': PropTypes.number,
        'width': PropTypes.string,
        'widthOrder': PropTypes.number,
        'quantity': PropTypes.number
      })
```

Is above correct usage? Or below?

```
'productItems': ImmutablePropTypes.mapOf(
ImmutablePropTypes.contains({
        'upc': PropTypes.string,
        'erpItemNumber': PropTypes.string,
        'onHandQuantity': PropTypes.number,
        'vendorQuantity': PropTypes.number,
        'disabled': PropTypes.bool,
        'hideOnSite': PropTypes.bool,
        'size': PropTypes.string,
        'sizeOrder': PropTypes.number,
        'width': PropTypes.string,
        'widthOrder': PropTypes.number,
        'quantity': PropTypes.number
      }))
```

any real difference between the two?

I am also confused by the note in contains to not use for lists, yet in readme example that is exactly how it's used:

```
var MyReactComponent = React.createClass({
    // ...
    propTypes: {
        myRequiredImmutableList: ImmutablePropTypes.listOf(
            ImmutablePropTypes.contains({
                someNumberProp: React.PropTypes.number.isRequired
            })
        ).isRequired
    }
    // ...
});
```
Some clarification here would be much appreciated.

**Comment by Aldredcz** [comment]
@ericlau-solid 
I'll try to explain:
The most important difference between `mapOf` and `contains` is that the first one describes collection of items (Map) and the second one is describing actual structure (Record, Shape,..)

Therefore `contains` accept as a parameter object, `mapOf` accepts another PropType validation function that is applied to every item in collection. So your first snippet is invalid, second one is valid and if you pass as a prop this data:

```
Immutable.Map({
    first: Immutable.Map({
        upc: 'upc of first item',
        erpItemNumber: 'erpItemNumber of first item,
        onHandQuantity: 1,
        vendorQuantity: 1,
        disabled: false,
        hideOnSite: false,
        size: 'size of first item',
        sizeOrder: 1,
        width: 'width of first item',
        widthOrder: 1,
        quantity: 1
    }),
    second: Immutable.Map({
        upc: 'upc of second item',
        erpItemNumber: 'erpItemNumber of second item,
        onHandQuantity: 2,
        vendorQuantity: 2,
        disabled: true,
        hideOnSite: false,
        size: 'size of second item',
        sizeOrder: 2,
        width: 'width of second item',
        widthOrder: 2,
        quantity: 2
    }),
   ...
})
```
then it's also correct. Another thing is, that this use case is not very common. For collections you might wan't to use `List` or `OrderedMap` (as it guarantees items order). That is actually the example in your last snippet.

---

> I am also confused by the note in contains to not use for lists, yet in readme example that is exactly how it's used:

I'd love to explain, but couldn't find a way to explain it better than `README.md`. 
```
// ...
aMap: ImmutablePropTypes.contains({
    aList: ImmutablePropTypes.contains({
        0: React.PropTypes.number,
        1: React.PropTypes.string,
        2: React.PropTypes.number.isRequired,
    }).isRequired,
})
```
Maybe this might help:
~~`<SomeComponent aList={Immutable.fromJS({aList: [1, 'two', 3]})} />`~~
`<SomeComponent aList={Immutable.Map({aList: Immutable.List([1, 'two', 3])})} />`

**Comment by HurricaneJames** [comment]
Yeah, you want the `contains` helper. `mapOf` is for checking that all values, and possibly keys (see PR #30), are of a specific type.
