### ISSUE TITLE
React v15.3.0

### ISSUE THREAD

**Issue by oliviertassinari** [HurricaneJames/react-immutable-proptypes#35]
We should make sure we support https://github.com/facebook/react/issues/7131 correctly.

**Comment by miinx** [comment]
Yes please! 

I've tried to upgrade our site to React 15.3.0 today but get warnings everywhere we use `contains()`, `mapContains()`, etc from `react-immutable-proptypes`.

There is info here about the fix required:  https://facebook.github.io/react/warnings/dont-call-proptypes.html#fixing-the-false-positive-in-third-party-proptypes

Hoping you're looking at this?

Cheers
Karen

**Comment by stavarengo** [comment]
+1
I'm looking forward to this fix too :)

**Comment by kayneb** [comment]
+1 waiting on this one too!

**Comment by johannessjoberg** [comment]
+ 1 
i'm looking forward as well!

**Comment by HurricaneJames** [comment]
I think https://github.com/HurricaneJames/react-immutable-proptypes/commit/f4edf84ca314399e6976e4299c5e25667f6679e1 fixes this. I published it as v2.1.0.

**Comment by HurricaneJames** [comment]
I wanted to get this out as quickly as possible for everybody, so I did not do testing as thoroughly as normal. I did smoke test it against a few cases in a project I have. The errors are suppressed and the library seems to still alert for bad props. Please re-open if you find a case I missed and I will get right on it.

**Comment by stavarengo** [comment]
So far so good.
I can even say how happy I am :)
Thanks @HurricaneJames
