### ISSUE TITLE
Huge performance penalty because of immutable props validation

### ISSUE THREAD

**Issue by sergiu-paraschiv** [HurricaneJames/react-immutable-proptypes#40]
`NODE_ENV=production` disables React's PropTypes but not ImmutablePropTypes.
After manually removing them I got a 75%(!!!) rendering speed improvement.

I'm using stuff ranging from

```
let somePropType = ImmutablePropTypes.mapContains({
    id: PropTypes.string.isRequired,
    name: PropTypes.string.isRequired,
    isProjectLeader: PropTypes.bool,
    isHidden: PropTypes.bool,
    projectLeaderColor: PropTypes.string,
    index: PropTypes.number
});
```

to 

`let listOfSomePropType = ImmutablePropTypes.listOf(somePropType).isRequired`

_Is there a way for me to disable validation in production?_

**Comment by HurricaneJames** [comment]
Interesting,

I was unaware that React ran proptype checking in production at all. I'll
take a look.

**Comment by sergiu-paraschiv** [comment]
It doesn't.
I use browserify to bundle and babelify to transpile my code.
That means I can set `NODE_ENV=production` and React should be bundled in production mode, where proptype checking is disabled.
And that works great, normal proptype checks are skipped entirely. The problem is it still runs the checks for Immutable proptypes.

**Comment by busticated** [comment]
@sergiu-paraschiv are you using `ImmutablePropTypes` outside of a react component's `.propTypes` field?

**Comment by sergiu-paraschiv** [comment]
No. Mixed PropTypes and ImmutablePropTypes.

**Comment by ali** [comment]
@sergiu-paraschiv ever figure out why the propType checks still happened here?

this might be useful if you're using babel: https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types

**Comment by sergiu-paraschiv** [comment]
No, never had time to investigate this. That plugin seems to do what I need, but why would I rely on a babel transform to do something React itself already does? The solution is for `react-immutable-proptypes` to fix this.

**Comment by maxkostow** [comment]
@sergiu-paraschiv are you talking about the performance penalty from constructing the propType checkers or doing the actual validation?

**Comment by sergiu-paraschiv** [comment]
Performance penalty comes from the actual validation. When you have an Immutable List of Maps of a certain shape the validation process is 75% of re-rendering time.

**Comment by dounan** [comment]
What version of React are you on? Also how are you doing the profiling? Just curious how you came to the conclusion that React was actually running the validation logic. I don't think I have seen this issue yet in my usage.
