### ISSUE TITLE
Immutable propType validation error with `listOf`

### ISSUE THREAD

**Issue by bencripps** [HurricaneJames/react-immutable-proptypes#41]
````js
static propTypes = {
    items: oneOfType([
        listOf(any),
        arrayOf(any)
    ]).isRequired
}
````

If I remove `listOf(any)`, I no longer receive the propType error. which react has posted info about here, https://facebook.github.io/react/warnings/dont-call-proptypes.html

>
Warning: You are manually calling a React.PropTypes validation function for the `items[24]` prop on `Selector`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
>

With the next rev of react, it looks like this will actually throw an error. Any plans on updating the module for the incoming change?

**Comment by afhole** [comment]
I assume this is fixed by https://github.com/HurricaneJames/react-immutable-proptypes/commit/f4edf84ca314399e6976e4299c5e25667f6679e1

**Comment by afhole** [comment]
Yep, 2.1.0 seems to fix this for me

**Comment by bencripps** [comment]
Awesome! I'll check it out later today.
