### ISSUE TITLE
Question: How to validate a List of Maps

### ISSUE THREAD

**Issue by wonbyte** [HurricaneJames/react-immutable-proptypes#45]
Hi, This is a question and not an issue. I have the following data:

    const todos = List.of(
      Map({ id: 1, text: 'React', status: 'active', editing: false }),
      Map({ id: 2, text: 'Redux', status: 'active', editing: false }),
      Map({ id: 1, text: 'Immutable', status: 'completed', editing: false })
    );

And I am wondering if this would be the correct way to write the prop validation:

```
TodoList.propTypes = {
  todos: ImmutablePropTypes.listOf(
    ImmutablePropTypes.contains({
      id: React.PropTypes.number,
      text: React.PropTypes.string,
      status: React.PropTypes.string,
      editing: React.PropTypes.bool
    })
  )
};
```

Is there any way instead of using the .contains that it could be something like:
```
todos: ImmutablePropTypes.listOf(
    ImmutablePropTypes.mapOf({
      ImmutablePropTypes.mapContains({
         id: React.PropTypes.number,
         text: React.PropTypes.string,
         status: React.PropTypes.string,
         editing: React.PropTypes.bool
    })
   })
  )
};
```
Thanks for any help.

**Comment by Bates550** [comment]
I don't see a reason not to use `contains` (and didn't see a reason mentioned in the docs), but if you wanted to rewrite your first example with `mapContains` it would look like this
```
todos: ImmutablePropTypes.listOf(
  ImmutablePropTypes.mapContains({
    id: React.PropTypes.number,
    text: React.PropTypes.string,
    status: React.PropTypes.string,
    editing: React.PropTypes.bool
  })
)
```
Note that this is identical to the example except that `mapContains` is used instead of `contains`. 

`mapOf` can be used if you want to validate both **keys**, which was already done with `mapContains` and `contains`, and **values**. I'm not entirely sure how you'd use this to actually validate values, but I think you'll get the same behavior of the previous example like this
```
todos: ImmutablePropTypes.listOf(
    ImmutablePropTypes.mapOf({
      ImmutablePropTypes.mapContains({
         id: React.PropTypes.number,
         text: React.PropTypes.string,
         status: React.PropTypes.string,
         editing: React.PropTypes.bool
    })
  })
)
```

**Comment by JuniorBoaventura** [comment]
@Bates550 I'm trying to use the example mentioned above but it doesn't seem to work for me. I don't get any warnings for the maps inside my list. Even if I change the type of country to bool I won't get any warnings.

```js
export const userShape = {
  _id: PropTypes.number.isRequired,
  firstName: PropTypes.string,
  lastName: PropTypes.string,
  gender: PropTypes.string,
  email: PropTypes.string,
  addresses: ImmutablePropTypes.listOf(ImmutablePropTypes.mapContains(addressShape)),
  phones: ImmutablePropTypes.listOf(ImmutablePropTypes.mapContains(phoneShape)),
};

export const addressShape = {
  _id: PropTypes.string.isRequired,
  country: PropTypes.string,
  zip: PropTypes.string,
  type: PropTypes.string,
  number: PropTypes.string,
  street: PropTypes.string,
  locality: PropTypes.string,
  primary: PropTypes.bool,
  test: PropTypes.number.isRequired,
};

export const phoneShape = {
  _id: PropTypes.string.isRequired,
  primary: PropTypes.bool,
  country: PropTypes.string,
  type: PropTypes.string,
  number: PropTypes.string,
};
```

**Comment by Bates550** [comment]
Hmm, it will give warnings that it is getting string but expected bool if I change country to bool. In trying to reproduce your example though I noticed that you're just passing objects to `mapContains`, which I think is incorrect. You need to wrap these objects in `mapContains` calls as well.

Here's a pared down and corrected version of the example you gave:
```
export const userShape = ImmutablePropTypes.mapContains({
  addresses: ImmutablePropTypes.listOf(ImmutablePropTypes.mapContains(addressShape)),
});

export const addressShape = ImmutablePropTypes.mapContains({
  country: PropTypes.string,
});
```

**Comment by JuniorBoaventura** [comment]
@Bates550 Thank you for you answer, I managed to make it work wrapping my objects with mapContains also changing the order of the declaration like below
 ```javascript
export const addressShape = ImmutablePropTypes .mapContains({});
export const phoneShape = ImmutablePropTypes .mapContains({});
export const userShape = ImmutablePropTypes .mapContains({});
```
