### ISSUE TITLE
Package/project name should be changed to "immutable-prop-types"

### ISSUE THREAD

**Issue by jaminthorns** [HurricaneJames/react-immutable-proptypes#52]
If it'd be too much trouble, then I completely understand, but the name of this package/project should be changed to `immutable-prop-types` to keep in line with how the `prop-types` project is named: https://github.com/facebook/prop-types

**Comment by arfordweb** [comment]
I agree.  I try to import from `react-immutable-prop-types` all the time.  `immutable-prop-types` seems appropriate.

**Comment by olwen1987** [comment]
+1.. this happens always
