### ISSUE TITLE
ImmutablePropTypes.shape does not work with eslint-plugin-react 2.6+

### ISSUE THREAD

**Issue by HurricaneJames** [HurricaneJames/react-immutable-proptypes#6]
[eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react) updated their react/prop-types validation to look closely at any propType named `shape`. This is bad behavior, but for very good reasons. Reasons so good, and probably so helpful in general, that it makes sense to rename `ImmutablePropType.shape` to something else. At the moment I think `ImmutablePropType.contains`.

Note: I will release this as v1.1, and it will still have the shape validator, but it is deprecated. Eventually, shape will go away in favor of `contains` or whatever is decided. Also, if I have time or somebody else has the desire, we could upgrade eslint-plugin-react to identify `contains` and try to match get and getIn the way it matches objects now.

**Comment by HurricaneJames** [comment]
This is linked to yannickcr/eslint-plugin-react#145.

**Comment by cassus** [comment]
I'd love to have that v1.1 release! :balloon:

**Comment by HurricaneJames** [comment]
This should be available on npmjs.com now. `shape` is still available if you do not care about yannickcr/eslint-plugin-react, though it is deprecated so could be removed in the future.

**Comment by HurricaneJames** [comment]
https://github.com/HurricaneJames/react-immutable-proptypes/releases/tag/1.1.0

**Comment by cassus** [comment]
Thank you, this was quick! :balloon: :balloon:
